-- =========================================================
-- SUPABASE SCHEMA SETUP FOR MISS FARIA ADMIN PAGE
-- Paste and run this SQL script in your Supabase Dashboard:
-- https://supabase.com/dashboard/project/zztddcwdortaitixvvky/sql
-- =========================================================

-- 1. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  sku TEXT,
  slug TEXT,
  description TEXT,
  "shortDescription" TEXT,
  brand TEXT,
  "basePrice" NUMERIC DEFAULT 0,
  "salePrice" NUMERIC DEFAULT 0,
  "costPrice" NUMERIC DEFAULT 0,
  "stockQuantity" INT DEFAULT 0,
  "lowStockThreshold" INT DEFAULT 10,
  "backorderSetting" TEXT DEFAULT 'allow',
  weight NUMERIC DEFAULT 0,
  dimensions JSONB,
  "unitType" TEXT DEFAULT 'metric',
  attributes JSONB,
  variations JSONB,
  "mainImage" TEXT,
  "galleryImages" JSONB,
  "videoUrls" JSONB,
  "altText" TEXT,
  "primaryCategory" TEXT,
  "subCategories" JSONB,
  tags JSONB,
  "relatedProducts" JSONB,
  "upSellProducts" JSONB,
  "metaTitle" TEXT,
  "metaDescription" TEXT,
  "metaKeywords" JSONB,
  "shippingClass" TEXT,
  "packageWeight" NUMERIC,
  "packageDimensions" JSONB,
  "freeShipping" BOOLEAN DEFAULT false,
  "publishStatus" TEXT DEFAULT 'published',
  visibility TEXT DEFAULT 'public',
  featured BOOLEAN DEFAULT false,
  "createdAt" TEXT,
  "updatedAt" TEXT
);

-- 2. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY,
  customer TEXT,
  email TEXT,
  date TEXT,
  items INT DEFAULT 1,
  total NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Pending',
  "paymentMethod" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. CUSTOMERS TABLE
CREATE TABLE IF NOT EXISTS public.customers (
  id TEXT PRIMARY KEY,
  name TEXT,
  email TEXT,
  "ordersCount" INT DEFAULT 0,
  "totalSpent" NUMERIC DEFAULT 0,
  tier TEXT DEFAULT 'New Member',
  status TEXT DEFAULT 'Active',
  joined TEXT
);

-- 5. SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
  id INT PRIMARY KEY DEFAULT 1,
  "storeName" TEXT,
  "contactEmail" TEXT,
  currency TEXT,
  "lowStockGlobalThreshold" INT,
  "defaultWeightUnit" TEXT,
  "defaultDimensionUnit" TEXT,
  "freeShippingThreshold" NUMERIC,
  "autoGenerateSKU" BOOLEAN,
  theme TEXT
);

-- 6. ANNOUNCEMENT BAR TABLE
CREATE TABLE IF NOT EXISTS public.announcement_bar (
  id INT PRIMARY KEY DEFAULT 1,
  "enabled" BOOLEAN DEFAULT true,
  "tickerText" TEXT DEFAULT '🚀 Flash Sale! Enjoy up to 50% OFF on premium audio gear. Free express shipping on orders over $100! Use Code: FARIA50',
  "scrollSpeed" TEXT DEFAULT 'normal', -- 'slow', 'normal', 'fast'
  "bgColor" TEXT DEFAULT '#4f46e5',
  "textColor" TEXT DEFAULT '#ffffff',
  "fontSize" INT DEFAULT 13,
  "enableRightDetails" BOOLEAN DEFAULT true,
  "rightDetailText" TEXT DEFAULT '📞 Helpline: +1 (800) 555-0199',
  "rightBadgeText" TEXT DEFAULT 'SPECIAL OFFER',
  "rightLinkText" TEXT DEFAULT 'Shop Flash Sale',
  "rightLinkUrl" TEXT DEFAULT '/catalog',
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. TRUST BADGES TABLE
CREATE TABLE IF NOT EXISTS public.trust_badges (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  subtitle TEXT,
  icon TEXT DEFAULT 'ShieldCheck',
  "iconColor" TEXT DEFAULT '#6366f1',
  "bgColor" TEXT DEFAULT 'rgba(99, 102, 241, 0.1)',
  "active" BOOLEAN DEFAULT true,
  position INT DEFAULT 1
);

-- 8. BUNDLE OFFERS TABLE
CREATE TABLE IF NOT EXISTS public.bundle_offers (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  "productIds" JSONB,
  "discountType" TEXT DEFAULT 'percentage', -- 'percentage', 'fixed', 'override'
  "discountValue" NUMERIC DEFAULT 15,
  "bundlePrice" NUMERIC DEFAULT 0,
  badge TEXT DEFAULT 'BEST VALUE',
  active BOOLEAN DEFAULT true,
  "createdAt" TEXT
);

-- 9. STOCK COUNTERS TABLE
CREATE TABLE IF NOT EXISTS public.stock_counters (
  id INT PRIMARY KEY DEFAULT 1,
  "enableCountdown" BOOLEAN DEFAULT true,
  "flashSaleTitle" TEXT DEFAULT '⚡ Limited Time Mega Deal!',
  "flashSaleEnd" TEXT,
  "enableScarcityCounter" BOOLEAN DEFAULT true,
  "lowStockThreshold" INT DEFAULT 10,
  "urgencyTextTemplate" TEXT DEFAULT '🔥 Hurry! Only {stock} units left in stock for this deal!',
  "progressBarColor" TEXT DEFAULT '#ef4444',
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 10. FAQS TABLE
CREATE TABLE IF NOT EXISTS public.faqs (
  id TEXT PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  category TEXT DEFAULT 'General',
  active BOOLEAN DEFAULT true,
  position INT DEFAULT 1
);

-- 11. REVIEWS TABLE
CREATE TABLE IF NOT EXISTS public.reviews (
  id TEXT PRIMARY KEY,
  "productId" TEXT,
  "productTitle" TEXT,
  "reviewerName" TEXT NOT NULL,
  "reviewerEmail" TEXT,
  rating INT DEFAULT 5,
  title TEXT,
  comment TEXT NOT NULL,
  status TEXT DEFAULT 'Approved', -- 'Approved', 'Pending', 'Rejected'
  verified BOOLEAN DEFAULT true,
  avatar TEXT,
  date TEXT
);

-- =========================================================
-- ROW LEVEL SECURITY (RLS) POLICIES FOR NEW TABLES
-- =========================================================
ALTER TABLE public.announcement_bar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trust_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bundle_offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_counters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public access announcement_bar" ON public.announcement_bar;
CREATE POLICY "Allow public access announcement_bar" ON public.announcement_bar FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access trust_badges" ON public.trust_badges;
CREATE POLICY "Allow public access trust_badges" ON public.trust_badges FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access bundle_offers" ON public.bundle_offers;
CREATE POLICY "Allow public access bundle_offers" ON public.bundle_offers FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access stock_counters" ON public.stock_counters;
CREATE POLICY "Allow public access stock_counters" ON public.stock_counters FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access faqs" ON public.faqs;
CREATE POLICY "Allow public access faqs" ON public.faqs FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access reviews" ON public.reviews;
CREATE POLICY "Allow public access reviews" ON public.reviews FOR ALL USING (true) WITH CHECK (true);

